name=LinApprox
version=1.0.0
author=Hompain
maintainer=Hompain
sentence=Simple linear approximation for different numbers of coefficients.
paragraph=Simple linear approximation for different numbers of coefficients.
category=Data Processing
url=https://github.com/HOMPAIN/LinApprox
architectures=*
